/**
 * Reminder records and payloads — the PHI-disciplined data model of B8.
 *
 * PHI DISCIPLINE (hard requirement, observability precedent):
 * reminder payloads reference task/metric/window ids and CALLER-VETTED
 * human-safe labels ONLY. They never carry observation values, units,
 * evidence content or references, concept codes, person identifiers, or
 * free text of any kind generated by the engine. The engine performs
 * structural pass-through of `ReminderLabelPack` entries; label content
 * is the authorized caller's responsibility (see README). Every payload
 * variant is covered by no-PHI proofs in `phi.test.ts`.
 *
 * NON-AUTHORITATIVE OUTPUT (operating rule): reminders nudge. A payload
 * is scheduling data, never a clinical assertion, never a punishment,
 * never a gamification signal. The fallback-offer rung OFFERS the
 * fallback vocabulary recorded on the task — the engine never orders a
 * provider, never ranks beyond the recorded method chain, and never
 * applies any restriction (authorized restriction application belongs to
 * the adherence lane, and then only if configured).
 */
import type { PersonId, PlanId, TaskId } from "@orbb/domain";
import type { MeasurementWindow } from "@orbb/measurement";
import type { ReminderId, WindowKey } from "./ids.js";

// ---------------------------------------------------------------------------
// Escalation ladder (gentle, two rungs by design).
// ---------------------------------------------------------------------------

/**
 * The escalation ladder. `REMIND` is the plain nudge (upcoming-due or
 * missed-window); `REMIND_WITH_FALLBACK_OFFER` adds the task's recorded
 * fallback vocabulary (journey #7's fallback-provider offer — DATA, not a
 * decision). There are deliberately no further rungs.
 */
export const ESCALATION_RUNGS = ["REMIND", "REMIND_WITH_FALLBACK_OFFER"] as const;

export type EscalationRung = (typeof ESCALATION_RUNGS)[number];

/** Type guard: is `value` an escalation rung? */
export function isEscalationRung(value: unknown): value is EscalationRung {
  return (
    typeof value === "string" &&
    (ESCALATION_RUNGS as readonly string[]).includes(value)
  );
}

/** Ladder order index of a rung (0 for `REMIND`, 1 for the offer rung). */
export function rungOrder(rung: EscalationRung): number {
  return ESCALATION_RUNGS.indexOf(rung);
}

// ---------------------------------------------------------------------------
// Reminder reasons.
// ---------------------------------------------------------------------------

/** Why a `REMIND`-family reminder exists. */
export const REMINDER_REASONS = ["upcoming-due", "missed-window"] as const;

export type ReminderReason = (typeof REMINDER_REASONS)[number];

// ---------------------------------------------------------------------------
// Payloads (what a channel renders; PHID-safe by construction).
// ---------------------------------------------------------------------------

/** One offered fallback capture path (method id + optional human-safe label). */
export interface FallbackMethodOffer {
  readonly methodId: string;
  readonly label?: string;
}

/** Fields shared by every reminder payload variant. */
export interface ReminderPayloadBase {
  readonly taskId: TaskId;
  readonly planId: PlanId;
  readonly metricId: string;
  /** Human-safe metric label, caller-vetted via the label pack. */
  readonly metricLabel?: string;
  readonly windowSequence: number;
  readonly windowOpensAt: Date;
  readonly windowClosesAt: Date;
  readonly reason: ReminderReason;
}

/** Payload of the plain `REMIND` rung. */
export interface RemindPayload extends ReminderPayloadBase {
  readonly kind: "remind";
}

/**
 * Payload of the `REMIND_WITH_FALLBACK_OFFER` rung: the task's recorded
 * fallback vocabulary (the compiled method chain after the preferred
 * method), offered as data. The chain order is the RECORDED order on the
 * task — the engine adds no ranking and makes no choice.
 */
export interface FallbackOfferPayload extends ReminderPayloadBase {
  readonly kind: "remind-with-fallback-offer";
  /** The preferred method recorded on the task (`methodOrder[0]`). */
  readonly preferredMethodId?: string;
  /** Human-safe label of the preferred method, caller-vetted. */
  readonly preferredMethodLabel?: string;
  /** The offered fallback vocabulary (`methodOrder` after the preferred method). */
  readonly fallbackMethods: readonly FallbackMethodOffer[];
}

/** The discriminated union of every payload variant. */
export type ReminderPayload = RemindPayload | FallbackOfferPayload;

// ---------------------------------------------------------------------------
// Reminder record.
// ---------------------------------------------------------------------------

/**
 * One planned reminder. `nominalSendAt` is the ladder's nominal instant
 * (window end minus lead, window end, or window end plus escalation
 * grace); `sendAt` is the EFFECTIVE instant after the defer-not-drop
 * quiet-hours rule (`deferredFrom` present exactly when deferral was
 * applied); `due` is `sendAt <= now`. `personId` is engine-internal
 * routing/audit scoping — it never enters the channel payload.
 */
export interface Reminder {
  readonly id: ReminderId;
  readonly taskId: TaskId;
  readonly planId: PlanId;
  readonly personId: PersonId;
  readonly metricId: string;
  readonly windowKey: WindowKey;
  readonly window: MeasurementWindow;
  readonly rung: EscalationRung;
  readonly channelId: string;
  readonly reason: ReminderReason;
  readonly nominalSendAt: Date;
  readonly sendAt: Date;
  /** Present exactly when quiet hours deferred this reminder. */
  readonly deferredFrom?: Date;
  readonly due: boolean;
  readonly payload: ReminderPayload;
}

/** Deterministic reminder ordering: task, window, rung, channel, send, id. */
export function compareReminders(a: Reminder, b: Reminder): number {
  if (a.taskId !== b.taskId) {
    return a.taskId < b.taskId ? -1 : 1;
  }
  if (a.windowKey !== b.windowKey) {
    return a.windowKey < b.windowKey ? -1 : 1;
  }
  const byRung = rungOrder(a.rung) - rungOrder(b.rung);
  if (byRung !== 0) {
    return byRung;
  }
  if (a.channelId !== b.channelId) {
    return a.channelId < b.channelId ? -1 : 1;
  }
  const bySend = a.sendAt.getTime() - b.sendAt.getTime();
  if (bySend !== 0) {
    return bySend;
  }
  return a.id < b.id ? -1 : 1;
}

// ---------------------------------------------------------------------------
// Defensive copies (stores and channels hand reminder data across seams).
// ---------------------------------------------------------------------------

function cloneDate(date: Date): Date {
  return new Date(date.getTime());
}

/** Deep-defensive copy of any payload variant (dates, offers, labels). */
export function cloneReminderPayload(payload: ReminderPayload): ReminderPayload {
  const base = {
    taskId: payload.taskId,
    planId: payload.planId,
    metricId: payload.metricId,
    ...(payload.metricLabel !== undefined ? { metricLabel: payload.metricLabel } : {}),
    windowSequence: payload.windowSequence,
    windowOpensAt: cloneDate(payload.windowOpensAt),
    windowClosesAt: cloneDate(payload.windowClosesAt),
    reason: payload.reason,
  };
  if (payload.kind === "remind") {
    return { kind: "remind", ...base };
  }
  return {
    kind: "remind-with-fallback-offer",
    ...base,
    ...(payload.preferredMethodId !== undefined
      ? {
          preferredMethodId: payload.preferredMethodId,
          ...(payload.preferredMethodLabel !== undefined
            ? { preferredMethodLabel: payload.preferredMethodLabel }
            : {}),
        }
      : {}),
    fallbackMethods: payload.fallbackMethods.map((offer) => ({
      methodId: offer.methodId,
      ...(offer.label !== undefined ? { label: offer.label } : {}),
    })),
  };
}

/** Deep-defensive copy of a reminder record. */
export function cloneReminder(reminder: Reminder): Reminder {
  return {
    ...reminder,
    window: {
      sequence: reminder.window.sequence,
      startsAt: cloneDate(reminder.window.startsAt),
      endsAt: cloneDate(reminder.window.endsAt),
    },
    nominalSendAt: cloneDate(reminder.nominalSendAt),
    sendAt: cloneDate(reminder.sendAt),
    ...(reminder.deferredFrom !== undefined
      ? { deferredFrom: cloneDate(reminder.deferredFrom) }
      : {}),
    payload: cloneReminderPayload(reminder.payload),
  };
}
